


user_delete:
    path:     /user/{id}
    controller: App\Controller\UserController::delete
    methods:   [DELETE]

user_update:
    path:     /user/{id}
    controller: App\Controller\UserController::update
    methods:   [PUT]